language: haskell
before_install:
  - "cabal update"
  - "cabal install shellcheck"
install: true
script:
  - "shellcheck *.sh"
  - ". setup-environment.sh"
  - 'echo "Testing exported variable: $CM_SOFTWARE_BUILD_NODES"'
