language: haskell
before_install:
  - "cabal update"
  - "cabal install shellcheck"
# Below, the "install: true" item, means that we'll skip the (Haskell/Cabal) install step.
# More info: http://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true
script:
  - "shellcheck *.sh"
  - ". setup-environment.sh"
  - 'echo "Testing exported variable: $CM_SOFTWARE_BUILD_NODES"'
notifications:
  email:
    - brian@bioconductor.org
